module.exports = {
  schemaFile: process.env.RTK_QUERY_SCENARIO_MANAGEMENT_OPENAPI_FILE,
  apiFile: './src/redux/apis/generatedApi.ts',
  apiImport: 'generatedApi',
  outputFile: './src/redux/apis/generatedScenarioManagementApi.ts',
  exportName: 'generatedScenarioManagementApi',
  filterEndpoints: [
    'getApiV2TestScenariosForResultLinkManagement',
    'getApiV2TestScenarioFolders',
    'postApiV2TestScenarioFolders',
    'patchApiV2TestScenarioFoldersByFolderId',
    'deleteApiV2TestScenarioFoldersByFolderId',
    'getApiV2TestSuites',
    'postApiV2TestSuites',
    'getApiV2TestSuitesBySuiteId',
    'patchApiV2TestSuitesBySuiteId',
    'deleteApiV2TestSuitesBySuiteId',
    'postApiV2TestSuitesBySuiteIdMembers',
    'deleteApiV2TestSuitesBySuiteIdMembers',
    'putApiV2TestSuitesBySuiteIdMembersOrder',
    'patchApiV2TestScenariosBulkFolder',
  ],
  tag: true,
  hooks: { queries: true, lazyQueries: true, mutations: true },
};
